<?xml version="1.0" encoding="utf-8"?>
<Database Name="govind" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SYSTEM;Initial Catalog=govind;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="govindConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.sample" Member="samples">
    <Type Name="sample">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Aud" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>